version: "2"
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:5.1.1"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: "confluentinc/cp-kafka:5.1.1"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.8.128:9092"
    depends_on:
      - zookeeper
